# ELT - Integração de Dados para Previsão de Evasão Escolar

Este notebook realiza o processo de **ELT (Extract, Load, Transform)** para integrar:

- Microdados do Censo Escolar
- Dados socioeconômicos municipais

Objetivo final:

Criar datasets analíticos que serão utilizados para **modelagem de machine learning para previsão de evasão escolar**.

Estrutura do pipeline:

RAW → SILVER → GOLD

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)

In [3]:
BASE_DIR = Path("data")

RAW = BASE_DIR / "raw"
SILVER = BASE_DIR / "silver"
GOLD = BASE_DIR / "gold"

MICRODADOS = RAW / "microdados_inep"
SOCIO = RAW / "socioeconomicos"

SILVER.mkdir(parents=True, exist_ok=True)
GOLD.mkdir(parents=True, exist_ok=True)

In [4]:
PATH_MATRICULA = MICRODADOS / "Tabela_Matricula_2025.csv"
PATH_ESCOLA = MICRODADOS / "Tabela_Escola_2025.csv"
PATH_TURMA = MICRODADOS / "Tabela_Turma_2025.csv"
PATH_DOCENTE = MICRODADOS / "Tabela_Docente_2025.csv"
PATH_GESTOR = MICRODADOS / "Tabela_Gestor_Escolar_2025.csv"

PATH_MUNICIPIOS = SOCIO / "base_municipios_brasileiros.csv"
PATH_SOCIO_EXTRA = SOCIO / "municipios.csv"

## Escola enriquecida

In [5]:
def load_csv(path):
    return pd.read_csv(
        path,
        sep=";",
        encoding="latin1",
        low_memory=False
    )

print("Carregando microdados...")

matricula = load_csv(PATH_MATRICULA)
escola = load_csv(PATH_ESCOLA)
turma = load_csv(PATH_TURMA)
docente = load_csv(PATH_DOCENTE)
gestor = load_csv(PATH_GESTOR)

print("Microdados carregados!")

Carregando microdados...
Microdados carregados!

In [6]:
def load_csv(path):
    return pd.read_csv(
        path,
        sep=",",
        encoding="latin1",
        low_memory=False
    )

print("Carregando municipios...")

municipios = load_csv(PATH_MUNICIPIOS)

print("Municipios carregados!")

Carregando municipios...
Municipios carregados!

In [7]:
print("Formato do dataset:")

print("matricula:", matricula.shape)
print("escola:", escola.shape)
print("turma:", turma.shape)
print("docente:", docente.shape)
print("gestor:", gestor.shape)
print("municipios:", municipios.shape)

Formato do dataset:
matricula: (178766, 237)
escola: (214192, 302)
turma: (178772, 190)
docente: (178772, 156)
gestor: (180540, 65)
municipios: (180285, 452)

In [8]:
print("Colunas da tabela escola")
print(escola.columns.tolist())

print("\nColunas da tabela municipios")
print(municipios.columns.tolist())

Colunas da tabela escola
['NU_ANO_CENSO', 'NO_REGIAO', 'CO_REGIAO', 'NO_UF', 'SG_UF', 'CO_UF', 'NO_MUNICIPIO', 'CO_MUNICIPIO', 'NO_REGIAO_GEOG_INTERM', 'CO_REGIAO_GEOG_INTERM', 'NO_REGIAO_GEOG_IMED', 'CO_REGIAO_GEOG_IMED', 'NO_MESORREGIAO', 'CO_MESORREGIAO', 'NO_MICRORREGIAO', 'CO_MICRORREGIAO', 'NO_DISTRITO', 'CO_DISTRITO', 'NO_REGIAO_ADMINISTRATIVA', 'CO_REGIAO_ADMINISTRATIVA', 'NO_ENTIDADE', 'CO_ENTIDADE', 'TP_DEPENDENCIA', 'TP_CATEGORIA_ESCOLA_PRIVADA', 'TP_LOCALIZACAO', 'TP_LOCALIZACAO_DIFERENCIADA', 'DS_ENDERECO', 'NU_ENDERECO', 'DS_COMPLEMENTO', 'NO_BAIRRO', 'CO_CEP', 'NU_DDD', 'NU_TELEFONE', 'LATITUDE', 'LONGITUDE', 'TP_SITUACAO_FUNCIONAMENTO', 'CO_ORGAO_REGIONAL', 'DT_ANO_LETIVO_INICIO', 'DT_ANO_LETIVO_TERMINO', 'IN_VINCULO_SECRETARIA_EDUCACAO', 'IN_VINCULO_SEGURANCA_PUBLICA', 'IN_VINCULO_SECRETARIA_SAUDE', 'IN_VINCULO_OUTRO_ORGAO', 'IN_PODER_PUBLICO_PARCERIA', 'TP_PODER_PUBLICO_PARCERIA', 'IN_FORMA_CONT_TERMO_COLABORA', 'IN_FORMA_CONT_TERMO_FOMENTO', 'IN_FORMA_CONT_ACORDO_COOP', 'IN_FORMA_CONT_PRESTACAO_SERV', 'IN_FORMA_CONT_COOP_TEC_FIN', 'IN_FORMA_CONT_CONSORCIO_PUB', 'IN_FORMA_CONT_MU_TERMO_COLAB', 'IN_FORMA_CONT_MU_TERMO_FOMENTO', 'IN_FORMA_CONT_MU_ACORDO_COOP', 'IN_FORMA_CONT_MU_PREST_SERV', 'IN_FORMA_CONT_MU_COOP_TEC_FIN', 'IN_FORMA_CONT_MU_CONSORCIO_PUB', 'IN_FORMA_CONT_ES_TERMO_COLAB', 'IN_FORMA_CONT_ES_TERMO_FOMENTO', 'IN_FORMA_CONT_ES_ACORDO_COOP', 'IN_FORMA_CONT_ES_PREST_SERV', 'IN_FORMA_CONT_ES_COOP_TEC_FIN', 'IN_FORMA_CONT_ES_CONSORCIO_PUB', 'IN_MANT_ESCOLA_PRIVADA_EMP', 'IN_MANT_ESCOLA_PRIVADA_ONG', 'IN_MANT_ESCOLA_PRIVADA_OSCIP', 'IN_MANT_ESCOLA_PRIV_ONG_OSCIP', 'IN_MANT_ESCOLA_PRIVADA_SIND', 'IN_MANT_ESCOLA_PRIVADA_SIST_S', 'IN_MANT_ESCOLA_PRIVADA_S_FINS', 'NU_CNPJ_ESCOLA_PRIVADA', 'NU_CNPJ_MANTENEDORA', 'TP_REGULAMENTACAO', 'TP_RESPONSAVEL_REGULAMENTACAO', 'CO_ESCOLA_SEDE_VINCULADA', 'CO_IES_OFERTANTE', 'IN_LOCAL_FUNC_PREDIO_ESCOLAR', 'TP_OCUPACAO_PREDIO_ESCOLAR', 'IN_LOCAL_FUNC_SOCIOEDUCATIVO', 'IN_LOCAL_FUNC_UNID_PRISIONAL', 'IN_LOCAL_FUNC_PRISIONAL_SOCIO', 'IN_LOCAL_FUNC_GALPAO', 'TP_OCUPACAO_GALPAO', 'IN_LOCAL_FUNC_SALAS_OUTRA_ESC', 'IN_LOCAL_FUNC_OUTROS', 'IN_PREDIO_COMPARTILHADO', 'IN_AGUA_POTAVEL', 'IN_AGUA_REDE_PUBLICA', 'IN_AGUA_POCO_ARTESIANO', 'IN_AGUA_CACIMBA', 'IN_AGUA_FONTE_RIO', 'IN_AGUA_INEXISTENTE', 'IN_AGUA_CARRO_PIPA', 'IN_ENERGIA_REDE_PUBLICA', 'IN_ENERGIA_GERADOR_FOSSIL', 'IN_ENERGIA_RENOVAVEL', 'IN_ENERGIA_INEXISTENTE', 'IN_ESGOTO_REDE_PUBLICA', 'IN_ESGOTO_FOSSA_SEPTICA', 'IN_ESGOTO_FOSSA_COMUM', 'IN_ESGOTO_FOSSA', 'IN_ESGOTO_INEXISTENTE', 'IN_LIXO_SERVICO_COLETA', 'IN_LIXO_QUEIMA', 'IN_LIXO_ENTERRA', 'IN_LIXO_DESTINO_FINAL_PUBLICO', 'IN_LIXO_DESCARTA_OUTRA_AREA', 'IN_TRATAMENTO_LIXO_SEPARACAO', 'IN_TRATAMENTO_LIXO_REUTILIZA', 'IN_TRATAMENTO_LIXO_RECICLAGEM', 'IN_TRATAMENTO_LIXO_INEXISTENTE', 'IN_ALMOXARIFADO', 'IN_AREA_VERDE', 'IN_AREA_PLANTIO', 'IN_AUDITORIO', 'IN_BANHEIRO', 'IN_BANHEIRO_EI', 'IN_BANHEIRO_PNE', 'IN_BANHEIRO_FUNCIONARIOS', 'IN_BANHEIRO_CHUVEIRO', 'IN_BIBLIOTECA', 'IN_BIBLIOTECA_SALA_LEITURA', 'IN_COZINHA', 'IN_DESPENSA', 'IN_DORMITORIO_ALUNO', 'IN_DORMITORIO_PROFESSOR', 'IN_LABORATORIO_CIENCIAS', 'IN_LABORATORIO_INFORMATICA', 'IN_LABORATORIO_EDUC_PROF', 'IN_PATIO_COBERTO', 'IN_PATIO_DESCOBERTO', 'IN_PARQUE_INFANTIL', 'IN_PISCINA', 'IN_QUADRA_ESPORTES', 'IN_QUADRA_ESPORTES_COBERTA', 'IN_QUADRA_ESPORTES_DESCOBERTA', 'IN_REFEITORIO', 'IN_SALA_ATELIE_ARTES', 'IN_SALA_MUSICA_CORAL', 'IN_SALA_ESTUDIO_DANCA', 'IN_SALA_MULTIUSO', 'IN_SALA_ESTUDIO_GRAVACAO', 'IN_SALA_OFICINAS_EDUC_PROF', 'IN_SALA_DIRETORIA', 'IN_SALA_LEITURA', 'IN_SALA_PROFESSOR', 'IN_SALA_REPOUSO_ALUNO', 'IN_SECRETARIA', 'IN_SALA_ATENDIMENTO_ESPECIAL', 'IN_TERREIRAO', 'IN_VIVEIRO', 'IN_DEPENDENCIAS_OUTRAS', 'IN_ACESSIBILIDADE_CORRIMAO', 'IN_ACESSIBILIDADE_ELEVADOR', 'IN_ACESSIBILIDADE_PISOS_TATEIS', 'IN_ACESSIBILIDADE_VAO_LIVRE', 'IN_ACESSIBILIDADE_RAMPAS', 'IN_ACESSIBILIDADE_SINAL_SONORO', 'IN_ACESSIBILIDADE_SINAL_TATIL', 'IN_ACESSIBILIDADE_SINAL_VISUAL', 'IN_ACESSIBILIDADE_INEXISTENTE', 'IN_ACESSIBILIDADE_SINALIZACAO', 'QT_SALAS_UTILIZADAS_DENTRO', 'QT_SALAS_UTILIZADAS_FORA', 'QT_SALAS_UTILIZADAS', 'QT_SALAS_UTILIZA_CLIMATIZADAS', 'QT_SALAS_UTILIZADAS_ACESSIVEIS', 'QT_SALAS_LEITURA', 'IN_EQUIP_PARABOLICA', 'IN_COMPUTADOR', 'IN_EQUIP_COPIADORA', 'IN_EQUIP_IMPRESSORA', 'IN_EQUIP_IMPRESSORA_MULT', 'IN_EQUIP_SCANNER', 'IN_EQUIP_NENHUM', 'IN_EQUIP_DVD', 'QT_EQUIP_DVD', 'IN_EQUIP_SOM', 'QT_EQUIP_SOM', 'IN_EQUIP_TV', 'QT_EQUIP_TV', 'IN_EQUIP_LOUSA_DIGITAL', 'QT_EQUIP_LOUSA_DIGITAL', 'IN_EQUIP_MULTIMIDIA', 'QT_EQUIP_MULTIMIDIA', 'IN_DESKTOP_ALUNO', 'QT_DESKTOP_ALUNO', 'IN_COMP_PORTATIL_ALUNO', 'QT_COMP_PORTATIL_ALUNO', 'IN_TABLET_ALUNO', 'QT_TABLET_ALUNO', 'IN_INTERNET', 'IN_INTERNET_ALUNOS', 'IN_INTERNET_ADMINISTRATIVO', 'IN_INTERNET_APRENDIZAGEM', 'IN_INTERNET_COMUNIDADE', 'IN_ACESSO_INTERNET_COMPUTADOR', 'IN_ACES_INTERNET_DISP_PESSOAIS', 'TP_REDE_LOCAL', 'IN_BANDA_LARGA', 'QT_PROF_ADMINISTRATIVOS', 'QT_PROF_SERVICOS_GERAIS', 'QT_PROF_BIBLIOTECARIO', 'QT_PROF_SAUDE', 'QT_PROF_COORDENADOR', 'QT_PROF_FONAUDIOLOGO', 'QT_PROF_NUTRICIONISTA', 'QT_PROF_PSICOLOGO', 'QT_PROF_ALIMENTACAO', 'QT_PROF_PEDAGOGIA', 'QT_PROF_SECRETARIO', 'QT_PROF_SEGURANCA', 'QT_PROF_MONITORES', 'QT_PROF_GESTAO', 'QT_PROF_ASSIST_SOCIAL', 'QT_PROF_TRAD_LIBRAS', 'QT_PROF_AGRICOLA', 'QT_PROF_REVISOR_BRAILLE', 'IN_ALIMENTACAO', 'IN_MATERIAL_PED_MULTIMIDIA', 'IN_MATERIAL_PED_INFANTIL', 'IN_MATERIAL_PED_CIENTIFICO', 'IN_MATERIAL_PED_DIFUSAO', 'IN_MATERIAL_PED_MUSICAL', 'IN_MATERIAL_PED_JOGOS', 'IN_MATERIAL_PED_ARTISTICAS', 'IN_MATERIAL_PED_PROFISSIONAL', 'IN_MATERIAL_PED_DESPORTIVA', 'IN_MATERIAL_PED_INDIGENA', 'IN_MATERIAL_PED_ETNICO', 'IN_MATERIAL_PED_CAMPO', 'IN_MATERIAL_PED_BIL_SURDOS', 'IN_MATERIAL_PED_AGRICOLA', 'IN_MATERIAL_PED_QUILOMBOLA', 'IN_MATERIAL_PED_EDU_ESP', 'IN_MATERIAL_PED_NENHUM', 'IN_EDUCACAO_INDIGENA', 'TP_INDIGENA_LINGUA', 'CO_LINGUA_INDIGENA_1', 'CO_LINGUA_INDIGENA_2', 'CO_LINGUA_INDIGENA_3', 'IN_EXAME_SELECAO', 'IN_RESERVA_PPI', 'IN_RESERVA_RENDA', 'IN_RESERVA_PUBLICA', 'IN_RESERVA_PCD', 'IN_RESERVA_OUTROS', 'IN_RESERVA_NENHUMA', 'IN_REDES_SOCIAIS', 'IN_ESPACO_ATIVIDADE', 'IN_ESPACO_EQUIPAMENTO', 'IN_ORGAO_ASS_PAIS', 'IN_ORGAO_ASS_PAIS_MESTRES', 'IN_ORGAO_CONSELHO_ESCOLAR', 'IN_ORGAO_GREMIO_ESTUDANTIL', 'IN_ORGAO_OUTROS', 'IN_ORGAO_NENHUM', 'TP_PROPOSTA_PEDAGOGICA', 'IN_EDUC_AMBIENTAL', 'IN_EDUC_AMB_CONTEUDO', 'IN_EDUC_AMB_CURRICULAR', 'IN_EDUC_AMB_EIXO', 'IN_EDUC_AMB_EVENTOS', 'IN_EDUC_AMB_PROJETOS', 'IN_EDUC_AMB_NENHUMA', 'TP_AEE', 'TP_ATIVIDADE_COMPLEMENTAR', 'TP_ITINERARIO_FORMATIVO', 'IN_ITINERARIO_APROFUNDAMENTO', 'IN_ITINERARIO_TECN_PROF', 'IN_ESCOLARIZACAO', 'IN_MEDIACAO_PRESENCIAL', 'IN_MEDIACAO_SEMIPRESENCIAL', 'IN_MEDIACAO_EAD', 'IN_ESPECIAL_EXCLUSIVA', 'IN_REGULAR', 'IN_EJA', 'IN_PROFISSIONALIZANTE', 'IN_COMUM_CRECHE', 'IN_COMUM_PRE', 'IN_COMUM_FUND_AI', 'IN_COMUM_FUND_AF', 'IN_COMUM_MEDIO_MEDIO', 'IN_COMUM_MEDIO_INTEGRADO', 'IN_COMUM_MEDIO_FIC', 'IN_COMUM_MEDIO_NORMAL', 'IN_ESP_EXCLUSIVA_CRECHE', 'IN_ESP_EXCLUSIVA_PRE', 'IN_ESP_EXCLUSIVA_FUND_AI', 'IN_ESP_EXCLUSIVA_FUND_AF', 'IN_ESP_EXCLUSIVA_MEDIO_MEDIO', 'IN_ESP_EXCLUSIVA_MEDIO_INTEGR', 'IN_ESP_EXCLUSIVA_MEDIO_FIC', 'IN_ESP_EXCLUSIVA_MEDIO_NORMAL', 'IN_COMUM_EJA_FUND', 'IN_COMUM_EJA_MEDIO', 'IN_COMUM_EJA_PROF', 'IN_ESP_EXCLUSIVA_EJA_FUND', 'IN_ESP_EXCLUSIVA_EJA_MEDIO', 'IN_ESP_EXCLUSIVA_EJA_PROF', 'IN_COMUM_PROF', 'IN_ESP_EXCLUSIVA_PROF']

Colunas da tabela municipios

In [9]:
escola.head()

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,NO_REGIAO_GEOG_INTERM,CO_REGIAO_GEOG_INTERM,NO_REGIAO_GEOG_IMED,CO_REGIAO_GEOG_IMED,NO_MESORREGIAO,CO_MESORREGIAO,NO_MICRORREGIAO,CO_MICRORREGIAO,NO_DISTRITO,CO_DISTRITO,NO_REGIAO_ADMINISTRATIVA,CO_REGIAO_ADMINISTRATIVA,NO_ENTIDADE,CO_ENTIDADE,TP_DEPENDENCIA,TP_CATEGORIA_ESCOLA_PRIVADA,TP_LOCALIZACAO,TP_LOCALIZACAO_DIFERENCIADA,DS_ENDERECO,NU_ENDERECO,DS_COMPLEMENTO,NO_BAIRRO,CO_CEP,NU_DDD,NU_TELEFONE,LATITUDE,LONGITUDE,TP_SITUACAO_FUNCIONAMENTO,CO_ORGAO_REGIONAL,DT_ANO_LETIVO_INICIO,DT_ANO_LETIVO_TERMINO,IN_VINCULO_SECRETARIA_EDUCACAO,IN_VINCULO_SEGURANCA_PUBLICA,IN_VINCULO_SECRETARIA_SAUDE,IN_VINCULO_OUTRO_ORGAO,IN_PODER_PUBLICO_PARCERIA,TP_PODER_PUBLICO_PARCERIA,IN_FORMA_CONT_TERMO_COLABORA,IN_FORMA_CONT_TERMO_FOMENTO,IN_FORMA_CONT_ACORDO_COOP,IN_FORMA_CONT_PRESTACAO_SERV,IN_FORMA_CONT_COOP_TEC_FIN,IN_FORMA_CONT_CONSORCIO_PUB,IN_FORMA_CONT_MU_TERMO_COLAB,IN_FORMA_CONT_MU_TERMO_FOMENTO,IN_FORMA_CONT_MU_ACORDO_COOP,IN_FORMA_CONT_MU_PREST_SERV,IN_FORMA_CONT_MU_COOP_TEC_FIN,IN_FORMA_CONT_MU_CONSORCIO_PUB,IN_FORMA_CONT_ES_TERMO_COLAB,IN_FORMA_CONT_ES_TERMO_FOMENTO,IN_FORMA_CONT_ES_ACORDO_COOP,IN_FORMA_CONT_ES_PREST_SERV,IN_FORMA_CONT_ES_COOP_TEC_FIN,IN_FORMA_CONT_ES_CONSORCIO_PUB,IN_MANT_ESCOLA_PRIVADA_EMP,IN_MANT_ESCOLA_PRIVADA_ONG,IN_MANT_ESCOLA_PRIVADA_OSCIP,IN_MANT_ESCOLA_PRIV_ONG_OSCIP,IN_MANT_ESCOLA_PRIVADA_SIND,IN_MANT_ESCOLA_PRIVADA_SIST_S,IN_MANT_ESCOLA_PRIVADA_S_FINS,NU_CNPJ_ESCOLA_PRIVADA,NU_CNPJ_MANTENEDORA,TP_REGULAMENTACAO,TP_RESPONSAVEL_REGULAMENTACAO,CO_ESCOLA_SEDE_VINCULADA,CO_IES_OFERTANTE,IN_LOCAL_FUNC_PREDIO_ESCOLAR,TP_OCUPACAO_PREDIO_ESCOLAR,IN_LOCAL_FUNC_SOCIOEDUCATIVO,IN_LOCAL_FUNC_UNID_PRISIONAL,IN_LOCAL_FUNC_PRISIONAL_SOCIO,IN_LOCAL_FUNC_GALPAO,TP_OCUPACAO_GALPAO,IN_LOCAL_FUNC_SALAS_OUTRA_ESC,IN_LOCAL_FUNC_OUTROS,IN_PREDIO_COMPARTILHADO,IN_AGUA_POTAVEL,IN_AGUA_REDE_PUBLICA,IN_AGUA_POCO_ARTESIANO,IN_AGUA_CACIMBA,IN_AGUA_FONTE_RIO,IN_AGUA_INEXISTENTE,IN_AGUA_CARRO_PIPA,IN_ENERGIA_REDE_PUBLICA,IN_ENERGIA_GERADOR_FOSSIL,IN_ENERGIA_RENOVAVEL,IN_ENERGIA_INEXISTENTE,IN_ESGOTO_REDE_PUBLICA,IN_ESGOTO_FOSSA_SEPTICA,IN_ESGOTO_FOSSA_COMUM,...,QT_PROF_BIBLIOTECARIO,QT_PROF_SAUDE,QT_PROF_COORDENADOR,QT_PROF_FONAUDIOLOGO,QT_PROF_NUTRICIONISTA,QT_PROF_PSICOLOGO,QT_PROF_ALIMENTACAO,QT_PROF_PEDAGOGIA,QT_PROF_SECRETARIO,QT_PROF_SEGURANCA,QT_PROF_MONITORES,QT_PROF_GESTAO,QT_PROF_ASSIST_SOCIAL,QT_PROF_TRAD_LIBRAS,QT_PROF_AGRICOLA,QT_PROF_REVISOR_BRAILLE,IN_ALIMENTACAO,IN_MATERIAL_PED_MULTIMIDIA,IN_MATERIAL_PED_INFANTIL,IN_MATERIAL_PED_CIENTIFICO,IN_MATERIAL_PED_DIFUSAO,IN_MATERIAL_PED_MUSICAL,IN_MATERIAL_PED_JOGOS,IN_MATERIAL_PED_ARTISTICAS,IN_MATERIAL_PED_PROFISSIONAL,IN_MATERIAL_PED_DESPORTIVA,IN_MATERIAL_PED_INDIGENA,IN_MATERIAL_PED_ETNICO,IN_MATERIAL_PED_CAMPO,IN_MATERIAL_PED_BIL_SURDOS,IN_MATERIAL_PED_AGRICOLA,IN_MATERIAL_PED_QUILOMBOLA,IN_MATERIAL_PED_EDU_ESP,IN_MATERIAL_PED_NENHUM,IN_EDUCACAO_INDIGENA,TP_INDIGENA_LINGUA,CO_LINGUA_INDIGENA_1,CO_LINGUA_INDIGENA_2,CO_LINGUA_INDIGENA_3,IN_EXAME_SELECAO,IN_RESERVA_PPI,IN_RESERVA_RENDA,IN_RESERVA_PUBLICA,IN_RESERVA_PCD,IN_RESERVA_OUTROS,IN_RESERVA_NENHUMA,IN_REDES_SOCIAIS,IN_ESPACO_ATIVIDADE,IN_ESPACO_EQUIPAMENTO,IN_ORGAO_ASS_PAIS,IN_ORGAO_ASS_PAIS_MESTRES,IN_ORGAO_CONSELHO_ESCOLAR,IN_ORGAO_GREMIO_ESTUDANTIL,IN_ORGAO_OUTROS,IN_ORGAO_NENHUM,TP_PROPOSTA_PEDAGOGICA,IN_EDUC_AMBIENTAL,IN_EDUC_AMB_CONTEUDO,IN_EDUC_AMB_CURRICULAR,IN_EDUC_AMB_EIXO,IN_EDUC_AMB_EVENTOS,IN_EDUC_AMB_PROJETOS,IN_EDUC_AMB_NENHUMA,TP_AEE,TP_ATIVIDADE_COMPLEMENTAR,TP_ITINERARIO_FORMATIVO,IN_ITINERARIO_APROFUNDAMENTO,IN_ITINERARIO_TECN_PROF,IN_ESCOLARIZACAO,IN_MEDIACAO_PRESENCIAL,IN_MEDIACAO_SEMIPRESENCIAL,IN_MEDIACAO_EAD,IN_ESPECIAL_EXCLUSIVA,IN_REGULAR,IN_EJA,IN_PROFISSIONALIZANTE,IN_COMUM_CRECHE,IN_COMUM_PRE,IN_COMUM_FUND_AI,IN_COMUM_FUND_AF,IN_COMUM_MEDIO_MEDIO,IN_COMUM_MEDIO_INTEGRADO,IN_COMUM_MEDIO_FIC,IN_COMUM_MEDIO_NORMAL,IN_ESP_EXCLUSIVA_CRECHE,IN_ESP_EXCLUSIVA_PRE,IN_ESP_EXCLUSIVA_FUND_AI,IN_ESP_EXCLUSIVA_FUND_AF,IN_ESP_EXCLUSIVA_MEDIO_MEDIO,IN_ESP_EXCLUSIVA_MEDIO_INTEGR,IN_ESP_EXCLUSIVA_MEDIO_FIC,IN_ESP_EXCLUSIVA_MEDIO_NORMAL,IN_COMUM_EJA_FUND,IN_COMUM_EJA_MEDIO,IN_COMUM_EJA_PROF,IN_ESP_EXCLUSIVA_EJA_FUND,IN_ESP_EXCLUSIVA_EJA_MEDIO,IN_ESP_EXCLUSIVA_EJA_PROF,IN_COMUM_PROF,IN_ESP_EXCLUSIVA_PROF
0,2025,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102,Cacoal,110005,Leste Rondoniense,2,Cacoal,6,Alta Floresta D'Oeste,110001505,NaN,NaN,EIEEF HAP BITT TUPARI,11022558,2,NaN,2,2.0,TERRA INDIGENA RIO BRANCO,S/N,ALDEIA COLORADO,RURAL,76954000,69.0,993784647.0,NaN,NaN,1,00015,10FEB2025:00:00:00,11DEC2025:00:00:00,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,171.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2025,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102,Cacoal,110005,Leste Rondoniense,2,Cacoal,6,Alta Floresta D'Oeste,110001505,NaN,NaN,CEEJA LUIZ VAZ DE CAMOES,11024275,2,NaN,1,0.0,AVENIDA RIO DE JANEIRO,4776,ESCOLA,CIDADE ALTA,76954000,69.0,36412656.0,-11.930957,-61.986513,1,00015,10FEB2025:00:00:00,24DEC2025:00:00:00,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,2.0,4.0,1.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2025,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102,Cacoal,110005,Leste Rondoniense,2,Cacoal,6,Alta Floresta D'Oeste,110001505,NaN,NaN,EMMEF 7 DE SETEMBRO,11024291,3,NaN,2,NaN,LINHA 60 COM A 140,NaN,NaN,NaN,76954000,69.0,36413630.0,-12.042845,-62.177576,2,00015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102,Cacoal,110005,Leste Rondoniense,2,Cacoal,6,Alta Floresta D'Oeste,110001505,NaN,NaN,EMEIEF BOA ESPERANCA,11024666,3,NaN,2,0.0,LINHA P 50 KM 22,NaN,ZONA RURAL,NaN,76954000,69.0,999005110.0,-12.129820,-61.993349,1,00015,06FEB2025:00:00:00,17DEC2025:00:00:00,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2025,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,Ji-Paraná,1102,Cacoal,110005,Leste Rondoniense,2,Cacoal,6,Alta Floresta D'Oeste,110001505,NaN,NaN,EEEFM EURIDICE LOPES PEDROSO,11024682,2,NaN,1,0.0,AVENIDA MATO GROSSO,3861,NaN,CENTRO,76954000,69.0,993589910.0,-11.927329,-61.995058,1,00015,10FEB2025:00:00:00,16DEC2025:00:00:00,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,16.0,11.0,1.0,0.0,3.0,2.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
municipios.head()

,Unnamed: 0,id_municipio,id_municipio_6,id_municipio_tse,id_municipio_rf,id_municipio_bcb,nome_municipio,capital_uf,id_comarca,id_regiao_saude,nome_regiao_saude,id_regiao_imediata,nome_regiao_imediata,id_regiao_intermediaria,nome_regiao_intermediaria,id_microrregiao,nome_microrregiao,id_mesorregiao,nome_mesorregiao,id_regiao_metropolitana,nome_regiao_metropolitana,ddd,id_uf,nome_uf,nome_regiao,amazonia_legal,centroide,dimensao_identificao,ano,populacao,prop_catolicos,prop_evangelicos_pentecostais,prop_evangelicos_missao,prop_espiritas,prop_matriz_africana,ano_censo,dimensao_populacao,total_desastres,total_pessoas_afetadas,total_danos_materiais,total_prejuizos_publicos,total_prejuizos_privados,total_desastres_climatologicos,total_pessoas_afetadas_climatologicos,total_danos_materiais_climatologicos,total_prejuizos_publicos_climatologicos,total_prejuizos_privados_climatologicos,total_desastres_hidrologicos,total_pessoas_afetadas_hidrologicos,total_danos_materiais_hidrologicos,total_prejuizos_publicos_hidrologicos,total_prejuizos_privados_hidrologicos,total_desastres_meteorologicos,total_pessoas_afetadas_meteorologicos,total_danos_materiais_meteorologicos,total_prejuizos_publicos_meteorologicos,total_prejuizos_privados_meteorologicos,total_desastres_outros,total_pessoas_afetadas_outros,total_danos_materiais_outros,total_prejuizos_publicos_outros,total_prejuizos_privados_outros,populacao_atendida_agua,populacao_atentida_esgoto,populacao_urbana,populacao_urbana_residente_agua,populacao_urbana_atendida_esgoto,extensao_rede_agua,extensao_rede_esgoto,quantidade_sede_municipal_agua,quantidade_sede_municipal_esgoto,quantidade_ligacao_total_agua,quantidade_ligacao_total_esgoto,quantidade_empregado,despesa_pessoal,arrecadacao_total,investimento_agua_municipio,investimento_agua_estado,investimento_agua_prestador,investimento_esgoto_municipio,investimento_esgoto_estado,investimento_esgoto_prestador,indice_atendimento_total_agua,indice_atendimento_esgoto_agua,id_municipio_nome,nm_uf,area_total_municipio,desmatado_total_municipio,desmatado_total_amazonia,desmatado_total_caatinga,desmatado_total_cerrado,desmatado_total_mata_atlantica,desmatado_total_pampa,desmatado_total_pantanal,proporcao_desmatado,lag_total_desmatado,taxa_crescimento_desmatamento_abs,id,capacidade_investimento_adaptacao,capacidade_investimento_adaptacao_classe,...,total_mortalidade_parda_feminino,total_mortalidade_branca_feminino,total_mortalidade_amarela_feminino,total_mortalidade_indigena_feminino,total_mortalidade_homicidio_branca,total_mortalidade_homicidio_preta,total_mortalidade_homicidio_parda,total_mortalidade_homicidio_amarela,total_mortalidade_homicidio_indigena,total_mortalidade_domicilio,total_mortalidade_homicidio_domicilio,total_mortalidade_alcool_domicilio,total_mortalidade_homicidio_feminino_domicilio,total_mortalidade_homicidio_masculino_domicilio,total_mortalidade_alcool_feminino_domicilio,total_mortalidade_alcool_masculino_domicilio,total_mortalidade_homicidio_branca_domicilio,total_mortalidade_homicidio_preta_domicilio,total_mortalidade_homicidio_parda_domicilio,total_mortalidade_homicidio_amarela_domicilio,total_mortalidade_homicidio_indigena_domicilio,quantidade_mortes_intervencao_policial_civil_fora_de_servico,quantidade_feminicidio,quantidade_mortes_intervencao_policial_militar_fora_de_servico,quantidade_furto_veiculos,quantidade_mortes_intervencao_policial_civil_em_servico,quantidade_estupro,quantidade_morte_policiais_civis_confronto_em_servico,quantidade_mortes_intervencao_policial_militar_em_servico,quantidade_mortes_policiais_confronto,quantidade_mortes_violentas_intencionais,quantidade_posse_uso_entorpecente,quantidade_morte_policiais_militares_fora_de_servico,quantidade_morte_policiais_civis_fora_de_servico,quantidade_latrocinio,quantidade_porte_ilegal_arma_de_fogo,quantidade_mortes_intervencao_policial,quantidade_roubo_furto_veiculos,quantidade_posse_ilegal_arma_de_fogo,quantidade_lesao_corporal_dolosa_violencia_domestica,quantidade_trafico_entorpecente,quantidade_roubo_veiculos,quantidade_lesao_corporal_morte,proporcao_mortes_intenvencao_policial_x_mortes_violentas_intencionais,quantidade_morte_policiais_militares_confronto_em_servico,quantidade_posse_ilegal_porte_ilegal_arma_de_fogo,grupo,quantidade_homicidio_doloso,dimensao_seguranca,total_acao,total_falhas_graves,montante_fiscalizado,montante_fiscalizado_falha_grave,prop_falhas_graves,montante_falhas_graves,dimensao_corrupcao,ln.pc.receita1920.sd,ln.admpub.1920.sd,ln.forcapub.1920.sd,ln.rail1920.sd,amc1920,ln.dist.coast.sd,ln.dist.capital.sd,estimativa_ano_fundacao,dimensao_historica,total_aptos_prefeitura,total_comparecimento_prefeitura,proporcao_comparecimento_prefeitura,proporcao_votos_nulos_prefeitura,proporcao_votos_nulos,turno,nep_prefeitura,fracionalizacao_prefeitura,total_aptos_camara_vereadores,total_comparecimento_camara_vereadores,proporcao_comparecimento_camara_vereadores,proporcao_votos_brancos_camara_vereadores,proporcao_votos_nulos_camara_vereadores,nep_camara_vereadores,fracionalizacao_camara_vereadores,ano_eleicao,prefeito_eleito,partido,numero_partido,pct_votos_eleito,partido_segundo_colocado,numero_segundo_colocado,pct_votos_segundo_colocado,margem_votos,margem_pct,sg_partido_governador_eleito,sg_partido_governador_segundo_lugar,composicao_coligacao_governador_eleito,composicao_coligacao_governador_segundo_lugar,nm_urna_governador_eleito,nm_urna_governador_segundo_lugar,pct_votos_governador_eleito,pct_votos_governador_segundo_lugar,alinhado_partido_governador,dimensao_eleicoes
0,1,1100338.0,110033.0,434.0,47.0,44516.0,Nova MamorÃ©,0.0,1100106.0,11004.0,Madeira-MamorÃ©,110001.0,Porto Velho,1101.0,Porto Velho,11001.0,Porto Velho,1101.0,Madeira-GuaporÃ©,NaN,NaN,69.0,11.0,RondÃ´nia,Norte,1.0,POINT(-64.6295025002404 -10.3822863210755),1.0,1991,7250.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.146064,0.20096,0.065607,11AMC2097001,0.965919,0.751197,1991.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1100338.0,110033.0,434.0,47.0,44516.0,Nova MamorÃ©,0.0,1100106.0,11004.0,Madeira-MamorÃ©,110001.0,Porto Velho,1101.0,Porto Velho,11001.0,Porto Velho,1101.0,Madeira-GuaporÃ©,NaN,NaN,69.0,11.0,RondÃ´nia,Norte,1.0,POINT(-64.6295025002404 -10.3822863210755),1.0,1992,7041.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.146064,0.20096,0.065607,11AMC2097001,0.965919,0.751197,1991.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1100338.0,110033.0,434.0,47.0,44516.0,Nova MamorÃ©,0.0,1100106.0,11004.0,Madeira-MamorÃ©,110001.0,Porto Velho,1101.0,Porto Velho,11001.0,Porto Velho,1101.0,Madeira-GuaporÃ©,NaN,NaN,69.0,11.0,RondÃ´nia,Norte,1.0,POINT(-64.6295025002404 -10.3822863210755),1.0,1993,6882.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.146064,0.20096,0.065607,11AMC2097001,0.965919,0.751197,1991.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1100338.0,110033.0,434.0,47.0,44516.0,Nova MamorÃ©,0.0,1100106.0,11004.0,Madeira-MamorÃ©,110001.0,Porto Velho,1101.0,Porto Velho,11001.0,Porto Velho,1101.0,Madeira-GuaporÃ©,NaN,NaN,69.0,11.0,RondÃ´nia,Norte,1.0,POINT(-64.6295025002404 -10.3822863210755),1.0,1994,6716.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.146064,0.20096,0.065607,11AMC2097001,0.965919,0.751197,1991.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1100338.0,110033.0,434.0,47.0,44516.0,Nova MamorÃ©,0.0,1100106.0,11004.0,Madeira-MamorÃ©,110001.0,Porto Velho,1101.0,Porto Velho,11001.0,Porto Velho,1101.0,Madeira-GuaporÃ©,NaN,NaN,69.0,11.0,RondÃ´nia,Norte,1.0,POINT(-64.6295025002404 -10.3822863210755),1.0,1995,6553.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.146064,0.20096,0.065607,11AMC2097001,0.965919,0.751197,1991.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
cols_escola = [
    "CO_ENTIDADE",
    "CO_MUNICIPIO",
    "CO_UF"
]

escola_sel = escola[cols_escola].copy()

In [12]:
cols_docente = [
    "CO_ENTIDADE",
    "QT_DOC_BAS",
    "QT_DOC_BAS_FEM",
    "QT_DOC_BAS_MASC"
]

docente_sel = docente[cols_docente].copy()

In [13]:
cols_gestor = [
    "CO_ENTIDADE",
    "QT_GEST_BAS"
]

gestor_sel = gestor[cols_gestor].copy()

In [14]:
escola_full = escola_sel.merge(
    docente_sel,
    on="CO_ENTIDADE",
    how="left"
)

In [15]:
print(escola_full.shape)

escola_full.head()

(214192, 6)

,CO_ENTIDADE,CO_MUNICIPIO,CO_UF,QT_DOC_BAS,QT_DOC_BAS_FEM,QT_DOC_BAS_MASC
0,11022558,1100015,11,1.0,0.0,1.0
1,11024275,1100015,11,9.0,5.0,4.0
2,11024291,1100015,11,NaN,NaN,NaN
3,11024666,1100015,11,13.0,10.0,3.0
4,11024682,1100015,11,44.0,24.0,20.0

In [16]:
gestor.columns.tolist()

['NU_ANO_CENSO',
 'CO_ENTIDADE',
 'QT_GEST_BAS',
 'QT_GEST_BAS_FEM',
 'QT_GEST_BAS_MASC',
 'QT_GEST_BAS_ND',
 'QT_GEST_BAS_BRANCA',
 'QT_GEST_BAS_PRETA',
 'QT_GEST_BAS_PARDA',
 'QT_GEST_BAS_AMARELA',
 'QT_GEST_BAS_INDIGENA',
 'QT_GEST_BAS_NACIO_BRASILEIRA',
 'QT_GEST_BAS_NACIO_ESTRANG',
 'QT_GEST_BAS_0_24',
 'QT_GEST_BAS_25_29',
 'QT_GEST_BAS_30_39',
 'QT_GEST_BAS_40_49',
 'QT_GEST_BAS_50_54',
 'QT_GEST_BAS_55_59',
 'QT_GEST_BAS_60_MAIS',
 'QT_GEST_BAS_PCD',
 'QT_GEST_BAS_ZR_URB',
 'QT_GEST_BAS_ZR_RUR',
 'QT_GEST_BAS_ZR_NA',
 'QT_GEST_BAS_ESCO_EF',
 'QT_GEST_BAS_ESCO_EM',
 'QT_GEST_BAS_ESCO_SUP_GRAD',
 'QT_GEST_BAS_ESCO_SUP_GRAD_LICEN',
 'QT_GEST_BAS_ESCO_SUP_GRAD_SLICEN',
 'QT_GEST_BAS_ESCO_SUP_POS_ESPEC',
 'QT_GEST_BAS_ESCO_SUP_POS_MESTRA',
 'QT_GEST_BAS_ESCO_SUP_POS_DOUTO',
 'QT_GEST_BAS_ESCO_SUP_POS_NENHUM',
 'QT_GEST_BAS_VINCULO_CONCUR',
 'QT_GEST_BAS_VINCULO_CONTRA',
 'QT_GEST_BAS_VINCULO_TERCEIR',
 'QT_GEST_BAS_VINCULO_CLT',
 'QT_GEST_BAS_DIRETOR',
 'QT_GEST_BAS_OUTRO',
 'QT_GEST_BAS_ACESSO_CARGO_PROP',
 'QT_GEST_BAS_ACESSO_CARGO_INDIC',
 'QT_GEST_BAS_ACESSO_CARGO_SEL',
 'QT_GEST_BAS_ACESSO_CARGO_CONC',
 'QT_GEST_BAS_ACESSO_CARGO_ELEIC',
 'QT_GEST_BAS_ACESSO_CARGO_P_SEL',
 'QT_GEST_BAS_ACESSO_CARGO_OUTRO',
 'QT_GEST_BAS_ESPEC_CRE',
 'QT_GEST_BAS_ESPEC_PRE_ESCOLA',
 'QT_GEST_BAS_ESPEC_ANOS_INICIAIS',
 'QT_GEST_BAS_ESPEC_ANOS_FINAIS',
 'QT_GEST_BAS_ESPEC_ENS_MEDIO',
 'QT_GEST_BAS_ESPEC_EJA',
 'QT_GEST_BAS_ESPEC_ED_ESPECIAL',
 'QT_GEST_BAS_ESPEC_BIL_SURDOS',
 'QT_GEST_BAS_ESPEC_ED_INDIGENA',
 'QT_GEST_BAS_ESPEC_CAMPO',
 'QT_GEST_BAS_ESPEC_AMBIENTAL',
 'QT_GEST_BAS_ESPEC_DIR_HUMANOS',
 'QT_GEST_BAS_ESPEC_DIV_SEXUAL',
 'QT_GEST_BAS_ESPEC_DIR_ADOLESC',
 'QT_GEST_BAS_ESPEC_AFRO',
 'QT_GEST_BAS_ESPEC_GESTAO',
 'QT_GEST_BAS_ESPEC_EDUC_TIC',
 'QT_GEST_BAS_ESPEC_OUTROS',
 'QT_GEST_BAS_ESPEC_NENHUM']

In [17]:
gestor_sel = (
    gestor
    .groupby("CO_ENTIDADE")
    .size()
    .reset_index(name="QT_GESTORES")
)

In [18]:
escola_full = escola_full.merge(
    gestor_sel,
    on="CO_ENTIDADE",
    how="left"
)

In [19]:
escola_full.head()

,CO_ENTIDADE,CO_MUNICIPIO,CO_UF,QT_DOC_BAS,QT_DOC_BAS_FEM,QT_DOC_BAS_MASC,QT_GESTORES
0,11022558,1100015,11,1.0,0.0,1.0,1.0
1,11024275,1100015,11,9.0,5.0,4.0,1.0
2,11024291,1100015,11,NaN,NaN,NaN,NaN
3,11024666,1100015,11,13.0,10.0,3.0,1.0
4,11024682,1100015,11,44.0,24.0,20.0,1.0

In [20]:
escola_full.to_parquet(
    SILVER / "escola_enriquecida.parquet",
    index=False
)

print("Tabela escola_enriquecida salva!")

Tabela escola_enriquecida salva!

## Turma enriquecida

In [21]:
cols_turma = [
    "CO_ENTIDADE",
    "QT_TUR_BAS",
    "QT_TUR_INF",
    "QT_TUR_FUND",
    "QT_TUR_MED",
    "QT_TUR_EJA",
    "QT_TUR_PROF"
]

turma_sel = turma[cols_turma].copy()

Colunas da tabela turma:
['NU_ANO_CENSO', 'CO_ENTIDADE', 'QT_TUR_BAS', 'QT_TUR_INF', 'QT_TUR_INF_CRE', 'QT_TUR_INF_PRE', 'QT_TUR_FUND', 'QT_TUR_FUND_AI', 'QT_TUR_FUND_AI_1', 'QT_TUR_FUND_AI_2', 'QT_TUR_FUND_AI_3', 'QT_TUR_FUND_AI_4', 'QT_TUR_FUND_AI_5', 'QT_TUR_FUND_AI_MULTIETAPA', 'QT_TUR_FUND_AF', 'QT_TUR_FUND_AF_6', 'QT_TUR_FUND_AF_7', 'QT_TUR_FUND_AF_8', 'QT_TUR_FUND_AF_9', 'QT_TUR_FUND_AF_MULTI', 'QT_TUR_FUND_AF_CORRFLUXO', 'QT_TUR_MED', 'QT_TUR_MED_PROP', 'QT_TUR_MED_PROP_1', 'QT_TUR_MED_PROP_2', 'QT_TUR_MED_PROP_3', 'QT_TUR_MED_PROP_4', 'QT_TUR_MED_PROP_NS', 'QT_TUR_MED_IFTP_CT', 'QT_TUR_MED_IFTP_CT_1', 'QT_TUR_MED_IFTP_CT_2', 'QT_TUR_MED_IFTP_CT_3', 'QT_TUR_MED_IFTP_CT_4', 'QT_TUR_MED_IFTP_CT_NS', 'QT_TUR_MED_IFTP_QP', 'QT_TUR_MED_IFTP_QP_1', 'QT_TUR_MED_IFTP_QP_2', 'QT_TUR_MED_IFTP_QP_3', 'QT_TUR_MED_IFTP_QP_4', 'QT_TUR_MED_IFTP_QP_NS', 'QT_TUR_MED_NM', 'QT_TUR_MED_NM_1', 'QT_TUR_MED_NM_2', 'QT_TUR_MED_NM_3', 'QT_TUR_MED_NM_4', 'QT_TUR_MED_IFA_EXC', 'QT_TUR_MED_IFTP_EXC', 'QT_TUR_MED_IFTP_EXC_QP', 'QT_TUR_MED_IFA', 'QT_TUR_MED_IFA_LING', 'QT_TUR_MED_IFA_MATE', 'QT_TUR_MED_IFA_CIENC', 'QT_TUR_MED_IFA_HUMA', 'QT_TUR_PROF', 'QT_TUR_PROF_TEC', 'QT_TUR_PROF_TEC_CONC', 'QT_TUR_PROF_TEC_SUBS', 'QT_TUR_PROF_TEC_MISTO', 'QT_TUR_PROF_TEC_IFTP_CT', 'QT_TUR_PROF_NAO_TEC', 'QT_TUR_PROF_IFTP_QP', 'QT_TUR_PROF_FIC_CONC', 'QT_TUR_EJA', 'QT_TUR_EJA_FUND', 'QT_TUR_EJA_FUND_NPROF', 'QT_TUR_EJA_FUND_AI', 'QT_TUR_EJA_FUND_AF', 'QT_TUR_EJA_FUND_FIC', 'QT_TUR_EJA_MED', 'QT_TUR_EJA_MED_NPROF', 'QT_TUR_EJA_MED_FIC', 'QT_TUR_EJA_MED_TEC', 'QT_TUR_ESP', 'QT_TUR_ESP_CC', 'QT_TUR_ESP_CE', 'QT_TUR_BAS_D', 'QT_TUR_BAS_DM', 'QT_TUR_BAS_DV', 'QT_TUR_BAS_N', 'QT_TUR_BAS_EAD', 'QT_TUR_INF_CRE_D', 'QT_TUR_INF_CRE_DM', 'QT_TUR_INF_CRE_DV', 'QT_TUR_INF_CRE_N', 'QT_TUR_INF_PRE_D', 'QT_TUR_INF_PRE_DM', 'QT_TUR_INF_PRE_DV', 'QT_TUR_INF_PRE_N', 'QT_TUR_FUND_D', 'QT_TUR_FUND_DM', 'QT_TUR_FUND_DV', 'QT_TUR_FUND_N', 'QT_TUR_FUND_AI_D', 'QT_TUR_FUND_AI_DM', 'QT_TUR_FUND_AI_DV', 'QT_TUR_FUND_AI_N', 'QT_TUR_FUND_AF_D', 'QT_TUR_FUND_AF_DM', 'QT_TUR_FUND_AF_DV', 'QT_TUR_FUND_AF_N', 'QT_TUR_MED_D', 'QT_TUR_MED_DM', 'QT_TUR_MED_DV', 'QT_TUR_MED_N', 'QT_TUR_MED_EAD', 'QT_TUR_PROF_D', 'QT_TUR_PROF_DM', 'QT_TUR_PROF_DV', 'QT_TUR_PROF_N', 'QT_TUR_PROF_EAD', 'QT_TUR_PROF_TEC_D', 'QT_TUR_PROF_TEC_DM', 'QT_TUR_PROF_TEC_DV', 'QT_TUR_PROF_TEC_N', 'QT_TUR_PROF_TEC_EAD', 'QT_TUR_EJA_D', 'QT_TUR_EJA_DM', 'QT_TUR_EJA_DV', 'QT_TUR_EJA_N', 'QT_TUR_EJA_EAD', 'QT_TUR_EJA_FUND_D', 'QT_TUR_EJA_FUND_DM', 'QT_TUR_EJA_FUND_DV', 'QT_TUR_EJA_FUND_N', 'QT_TUR_EJA_FUND_EAD', 'QT_TUR_EJA_MED_D', 'QT_TUR_EJA_MED_DM', 'QT_TUR_EJA_MED_DV', 'QT_TUR_EJA_MED_N', 'QT_TUR_EJA_MED_EAD', 'QT_TUR_ESP_D', 'QT_TUR_ESP_DM', 'QT_TUR_ESP_DV', 'QT_TUR_ESP_N', 'QT_TUR_ESP_EAD', 'QT_TUR_ESP_CC_D', 'QT_TUR_ESP_CC_DM', 'QT_TUR_ESP_CC_DV', 'QT_TUR_ESP_CC_N', 'QT_TUR_ESP_CC_EAD', 'QT_TUR_ESP_CE_D', 'QT_TUR_ESP_CE_DM', 'QT_TUR_ESP_CE_DV', 'QT_TUR_ESP_CE_N', 'QT_TUR_ESP_CE_EAD', 'QT_TUR_BAS_INT', 'QT_TUR_INF_INT', 'QT_TUR_INF_CRE_INT', 'QT_TUR_INF_PRE_INT', 'QT_TUR_FUND_INT', 'QT_TUR_FUND_AI_INT', 'QT_TUR_FUND_AF_INT', 'QT_TUR_MED_INT', 'QT_TUR_PROF_INT', 'QT_TUR_PROF_TEC_INT', 'QT_TUR_EJA_INT', 'QT_TUR_EJA_FUND_INT', 'QT_TUR_EJA_MED_INT', 'QT_TUR_ESP_INT', 'QT_TUR_ESP_CC_INT', 'QT_TUR_ESP_CE_INT', 'QT_TUR_BAS_DISC_LINGUA_PORT', 'QT_TUR_BAS_DISC_EDUC_FISICA', 'QT_TUR_BAS_DISC_ARTES', 'QT_TUR_BAS_DISC_LINGUA_ING', 'QT_TUR_BAS_DISC_LINGUA_ESPA', 'QT_TUR_BAS_DISC_LINGUA_FRANC', 'QT_TUR_BAS_DISC_LINGUA_OUTRA', 'QT_TUR_BAS_DISC_LIBRAS', 'QT_TUR_BAS_DISC_LINGUA_INDIG', 'QT_TUR_BAS_DISC_PORT_SEG_LINGUA', 'QT_TUR_BAS_DISC_MATEMATICA', 'QT_TUR_BAS_DISC_CIENCIAS', 'QT_TUR_BAS_DISC_FISICA', 'QT_TUR_BAS_DISC_QUIMICA', 'QT_TUR_BAS_DISC_BIOLOGIA', 'QT_TUR_BAS_DISC_HISTORIA', 'QT_TUR_BAS_DISC_GEOGRAFIA', 'QT_TUR_BAS_DISC_SOCIOLOGIA', 'QT_TUR_BAS_DISC_FILOSOFIA', 'QT_TUR_BAS_DISC_EST_SOCIAIS', 'QT_TUR_BAS_DISC_EST_SOCIAIS_SOCI', 'QT_TUR_BAS_DISC_INFO_COMPUTACAO', 'QT_TUR_BAS_DISC_ENSINO_RELIGIOSO', 'QT_TUR_BAS_DISC_PROFISSIONA', 'QT_TUR_BAS_DISC_ESTAGIO_SUPER', 'QT_TUR_BAS_DISC_PEDAGOGICAS', 'QT_TUR_BAS_DISC_PROJETO_DE_VIDA', 'QT_TUR_BAS_DISC_OUTRAS', 'QT_TUR_BAS_LIBRAS']

In [25]:
cols_turma = [
    "CO_ENTIDADE",
    "QT_TUR_BAS",
    "QT_TUR_INF",
    "QT_TUR_FUND",
    "QT_TUR_MED",
    "QT_TUR_EJA",
    "QT_TUR_PROF"
]

turma_sel = turma[cols_turma].copy()

In [26]:
turma_sel.head()

,CO_ENTIDADE,QT_TUR_BAS,QT_TUR_INF,QT_TUR_FUND,QT_TUR_MED,QT_TUR_EJA,QT_TUR_PROF
0,11000023,15,0,15,0,0,0
1,11000040,12,12,0,0,0,0
2,11000058,35,3,23,9,0,4
3,11000104,25,5,20,0,0,0
4,11000198,45,11,28,6,0,0

In [27]:
escola_enriquecida = pd.read_parquet(
    SILVER / "escola_enriquecida.parquet"
)

escola_turma = escola_enriquecida.merge(
    turma_sel,
    on="CO_ENTIDADE",
    how="left"
)

In [28]:
print(escola_turma.shape)

escola_turma.head()

(214192, 13)

,CO_ENTIDADE,CO_MUNICIPIO,CO_UF,QT_DOC_BAS,QT_DOC_BAS_FEM,QT_DOC_BAS_MASC,QT_GESTORES,QT_TUR_BAS,QT_TUR_INF,QT_TUR_FUND,QT_TUR_MED,QT_TUR_EJA,QT_TUR_PROF
0,11022558,1100015,11,1.0,0.0,1.0,1.0,4.0,0.0,4.0,0.0,0.0,0.0
1,11024275,1100015,11,9.0,5.0,4.0,1.0,6.0,0.0,0.0,0.0,6.0,0.0
2,11024291,1100015,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11024666,1100015,11,13.0,10.0,3.0,1.0,11.0,2.0,9.0,0.0,0.0,0.0
4,11024682,1100015,11,44.0,24.0,20.0,1.0,37.0,0.0,9.0,28.0,0.0,5.0

In [29]:
escola_turma.to_parquet(
    SILVER / "escola_turma_enriquecida.parquet",
    index=False
)

print("Tabela escola_turma_enriquecida salva!")

Tabela escola_turma_enriquecida salva!

In [30]:
print(len(matricula.columns))
print(matricula.columns.tolist())

237
['NU_ANO_CENSO', 'CO_ENTIDADE', 'QT_MAT_BAS', 'QT_MAT_INF', 'QT_MAT_INF_CRE', 'QT_MAT_INF_PRE', 'QT_MAT_FUND', 'QT_MAT_FUND_AI', 'QT_MAT_FUND_AI_1', 'QT_MAT_FUND_AI_2', 'QT_MAT_FUND_AI_3', 'QT_MAT_FUND_AI_4', 'QT_MAT_FUND_AI_5', 'QT_MAT_FUND_AF', 'QT_MAT_FUND_AF_6', 'QT_MAT_FUND_AF_7', 'QT_MAT_FUND_AF_8', 'QT_MAT_FUND_AF_9', 'QT_MAT_MED', 'QT_MAT_MED_PROP', 'QT_MAT_MED_PROP_1', 'QT_MAT_MED_PROP_2', 'QT_MAT_MED_PROP_3', 'QT_MAT_MED_PROP_4', 'QT_MAT_MED_PROP_NS', 'QT_MAT_MED_IFTP_CT', 'QT_MAT_MED_IFTP_CT_1', 'QT_MAT_MED_IFTP_CT_2', 'QT_MAT_MED_IFTP_CT_3', 'QT_MAT_MED_IFTP_CT_4', 'QT_MAT_MED_IFTP_CT_NS', 'QT_MAT_MED_IFTP_QP', 'QT_MAT_MED_IFTP_QP_1', 'QT_MAT_MED_IFTP_QP_2', 'QT_MAT_MED_IFTP_QP_3', 'QT_MAT_MED_IFTP_QP_4', 'QT_MAT_MED_IFTP_QP_NS', 'QT_MAT_MED_NM', 'QT_MAT_MED_NM_1', 'QT_MAT_MED_NM_2', 'QT_MAT_MED_NM_3', 'QT_MAT_MED_NM_4', 'QT_MAT_MED_IFA', 'QT_MAT_MED_IFA_LING', 'QT_MAT_MED_IFA_LING_MT', 'QT_MAT_MED_IFA_LING_OTME', 'QT_MAT_MED_IFA_LING_OE', 'QT_MAT_MED_IFA_MATE', 'QT_MAT_MED_IFA_MATE_MT', 'QT_MAT_MED_IFA_MATE_OTME', 'QT_MAT_MED_IFA_MATE_OE', 'QT_MAT_MED_IFA_CIENC', 'QT_MAT_MED_IFA_CIENC_MT', 'QT_MAT_MED_IFA_CIENC_OTME', 'QT_MAT_MED_IFA_CIENC_OE', 'QT_MAT_MED_IFA_HUMA', 'QT_MAT_MED_IFA_HUMA_MT', 'QT_MAT_MED_IFA_HUMA_OTME', 'QT_MAT_MED_IFA_HUMA_OE', 'QT_MAT_MED_ARTI_IFTP_CT', 'QT_MAT_MED_ARTI_IFTP_CT_MT', 'QT_MAT_MED_ARTI_IFTP_CT_OTME', 'QT_MAT_MED_ARTI_IFTP_CT_OE', 'QT_MAT_MED_ARTI_IFTP_QP', 'QT_MAT_MED_ARTI_IFTP_QP_MT', 'QT_MAT_MED_ARTI_IFTP_QP_OTME', 'QT_MAT_MED_ARTI_IFTP_QP_OE', 'QT_MAT_PROF', 'QT_MAT_PROF_TEC', 'QT_MAT_PROF_TEC_CONC', 'QT_MAT_PROF_TEC_SUBS', 'QT_MAT_PROF_TEC_IFTP_CT', 'QT_MAT_PROF_NAO_TEC', 'QT_MAT_PROF_IFTP_QP', 'QT_MAT_PROF_FIC_CONC', 'QT_MAT_EJA', 'QT_MAT_EJA_FUND', 'QT_MAT_EJA_FUND_NPROF', 'QT_MAT_EJA_FUND_AI', 'QT_MAT_EJA_FUND_AF', 'QT_MAT_EJA_FUND_FIC', 'QT_MAT_EJA_MED', 'QT_MAT_EJA_MED_NPROF', 'QT_MAT_EJA_MED_FIC', 'QT_MAT_EJA_MED_TEC', 'QT_MAT_ESP', 'QT_MAT_ESP_INF', 'QT_MAT_ESP_INF_CRE', 'QT_MAT_ESP_INF_PRE', 'QT_MAT_ESP_FUND', 'QT_MAT_ESP_FUND_AI', 'QT_MAT_ESP_FUND_AF', 'QT_MAT_ESP_MED', 'QT_MAT_ESP_PROF', 'QT_MAT_ESP_PROF_TEC', 'QT_MAT_ESP_EJA', 'QT_MAT_ESP_EJA_FUND', 'QT_MAT_ESP_EJA_MED', 'QT_MAT_ESP_CC', 'QT_MAT_ESP_CC_INF', 'QT_MAT_ESP_CC_INF_CRE', 'QT_MAT_ESP_CC_INF_PRE', 'QT_MAT_ESP_CC_FUND', 'QT_MAT_ESP_CC_FUND_AI', 'QT_MAT_ESP_CC_FUND_AF', 'QT_MAT_ESP_CC_MED', 'QT_MAT_ESP_CC_PROF', 'QT_MAT_ESP_CC_PROF_TEC', 'QT_MAT_ESP_CC_EJA', 'QT_MAT_ESP_CC_EJA_FUND', 'QT_MAT_ESP_CC_EJA_MED', 'QT_MAT_ESP_CE', 'QT_MAT_ESP_CE_INF', 'QT_MAT_ESP_CE_INF_CRE', 'QT_MAT_ESP_CE_INF_PRE', 'QT_MAT_ESP_CE_FUND', 'QT_MAT_ESP_CE_FUND_AI', 'QT_MAT_ESP_CE_FUND_AF', 'QT_MAT_ESP_CE_MED', 'QT_MAT_ESP_CE_PROF', 'QT_MAT_ESP_CE_PROF_TEC', 'QT_MAT_ESP_CE_EJA', 'QT_MAT_ESP_CE_EJA_FUND', 'QT_MAT_ESP_CE_EJA_MED', 'QT_MAT_BAS_FEM', 'QT_MAT_BAS_MASC', 'QT_MAT_BAS_ND', 'QT_MAT_BAS_BRANCA', 'QT_MAT_BAS_PRETA', 'QT_MAT_BAS_PARDA', 'QT_MAT_BAS_AMARELA', 'QT_MAT_BAS_INDIGENA', 'QT_MAT_BAS_0_3', 'QT_MAT_BAS_4_5', 'QT_MAT_BAS_6_10', 'QT_MAT_BAS_11_14', 'QT_MAT_BAS_15_17', 'QT_MAT_BAS_18_MAIS', 'QT_MAT_BAS_0_3_REF_31_03', 'QT_MAT_BAS_4_5_REF_31_03', 'QT_MAT_BAS_6_10_REF_31_03', 'QT_MAT_BAS_11_14_REF_31_03', 'QT_MAT_BAS_15_17_REF_31_03', 'QT_MAT_BAS_18_MAIS_REF_31_03', 'QT_MAT_BAS_D', 'QT_MAT_BAS_DM', 'QT_MAT_BAS_DV', 'QT_MAT_BAS_N', 'QT_MAT_BAS_EAD', 'QT_MAT_INF_CRE_D', 'QT_MAT_INF_CRE_DM', 'QT_MAT_INF_CRE_DV', 'QT_MAT_INF_CRE_N', 'QT_MAT_INF_PRE_D', 'QT_MAT_INF_PRE_DM', 'QT_MAT_INF_PRE_DV', 'QT_MAT_INF_PRE_N', 'QT_MAT_FUND_D', 'QT_MAT_FUND_DM', 'QT_MAT_FUND_DV', 'QT_MAT_FUND_N', 'QT_MAT_FUND_AI_D', 'QT_MAT_FUND_AI_DM', 'QT_MAT_FUND_AI_DV', 'QT_MAT_FUND_AI_N', 'QT_MAT_FUND_AF_D', 'QT_MAT_FUND_AF_DM', 'QT_MAT_FUND_AF_DV', 'QT_MAT_FUND_AF_N', 'QT_MAT_MED_D', 'QT_MAT_MED_DM', 'QT_MAT_MED_DV', 'QT_MAT_MED_N', 'QT_MAT_MED_EAD', 'QT_MAT_PROF_D', 'QT_MAT_PROF_DM', 'QT_MAT_PROF_DV', 'QT_MAT_PROF_N', 'QT_MAT_PROF_EAD', 'QT_MAT_PROF_TEC_D', 'QT_MAT_PROF_TEC_DM', 'QT_MAT_PROF_TEC_DV', 'QT_MAT_PROF_TEC_N', 'QT_MAT_PROF_TEC_EAD', 'QT_MAT_EJA_D', 'QT_MAT_EJA_DM', 'QT_MAT_EJA_DV', 'QT_MAT_EJA_N', 'QT_MAT_EJA_EAD', 'QT_MAT_EJA_FUND_D', 'QT_MAT_EJA_FUND_DM', 'QT_MAT_EJA_FUND_DV', 'QT_MAT_EJA_FUND_N', 'QT_MAT_EJA_FUND_EAD', 'QT_MAT_EJA_MED_D', 'QT_MAT_EJA_MED_DM', 'QT_MAT_EJA_MED_DV', 'QT_MAT_EJA_MED_N', 'QT_MAT_EJA_MED_EAD', 'QT_MAT_ESP_D', 'QT_MAT_ESP_DM', 'QT_MAT_ESP_DV', 'QT_MAT_ESP_N', 'QT_MAT_ESP_EAD', 'QT_MAT_ESP_CC_D', 'QT_MAT_ESP_CC_DM', 'QT_MAT_ESP_CC_DV', 'QT_MAT_ESP_CC_N', 'QT_MAT_ESP_CC_EAD', 'QT_MAT_ESP_CE_D', 'QT_MAT_ESP_CE_DM', 'QT_MAT_ESP_CE_DV', 'QT_MAT_ESP_CE_N', 'QT_MAT_ESP_CE_EAD', 'QT_MAT_BAS_INT', 'QT_MAT_INF_INT', 'QT_MAT_INF_CRE_INT', 'QT_MAT_INF_PRE_INT', 'QT_MAT_FUND_INT', 'QT_MAT_FUND_AI_INT', 'QT_MAT_FUND_AF_INT', 'QT_MAT_MED_INT', 'QT_MAT_PROF_INT', 'QT_MAT_PROF_TEC_INT', 'QT_MAT_EJA_INT', 'QT_MAT_EJA_FUND_INT', 'QT_MAT_EJA_MED_INT', 'QT_MAT_ESP_INT', 'QT_MAT_ESP_CC_INT', 'QT_MAT_ESP_CE_INT', 'QT_MAT_BAS_LIBRAS', 'QT_MAT_ZR_URB', 'QT_MAT_ZR_RUR', 'QT_MAT_ZR_NA', 'QT_TRANSP_PUBLICO', 'QT_TRANSP_RESP_EST', 'QT_TRANSP_RESP_MUN']